# Generated by Django 4.2.13 on 2024-08-24 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_alter_product_image_alter_product_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchase',
            old_name='purchased_at',
            new_name='purchase_date',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='product',
        ),
        migrations.AddField(
            model_name='purchase',
            name='product_id',
            field=models.IntegerField(default=0),
        ),
    ]
