# Generated by Django 4.2.13 on 2024-08-24 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_purchasedproduct_delete_purchase'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchasedproduct',
            name='product_id',
        ),
        migrations.AddField(
            model_name='purchasedproduct',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='web.product'),
        ),
    ]
