# Generated by Django 4.2.13 on 2024-08-25 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_remove_purchasedproduct_product_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='products/default.png', upload_to='products/'),
        ),
    ]
